import React from 'react';
import { 
  Pencil, 
  FilePlus2, 
  Image as ImageIcon, 
  ArrowRightLeft, 
  SplitSquareHorizontal, 
  Combine, 
  FileKey2, 
  Languages,
  Stamp
} from 'lucide-react';

export const ALL_TOOLS = [
  {
    id: 'edit',
    title: 'Editar PDF',
    description: 'Adicione texto, imagens, formas ou anotações a mão livre.',
    icon: Pencil,
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-50',
    path: '/editor',
  },
  {
    id: 'merge',
    title: 'Mesclar PDFs',
    description: 'Junte vários arquivos PDF em um único documento facilmente.',
    icon: Combine,
    color: 'text-purple-500',
    bgColor: 'bg-purple-50',
    path: '/tool/merge',
  },
  {
    id: 'split',
    title: 'Dividir PDF',
    description: 'Extraia páginas ou divida um PDF em vários arquivos menores.',
    icon: SplitSquareHorizontal,
    color: 'text-rose-500',
    bgColor: 'bg-rose-50',
    path: '/tool/split',
  },
  {
    id: 'compress',
    title: 'Comprimir PDF',
    description: 'Reduza o tamanho do arquivo preservando a melhor qualidade possível.',
    icon: FilePlus2,
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
    path: '/tool/compress',
  },
  {
    id: 'convert-to-word',
    title: 'PDF para Word',
    description: 'Converta seus PDFs em documentos DOCX fáceis de editar.',
    icon: ArrowRightLeft,
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    path: '/tool/pdf-to-word',
  },
  {
    id: 'convert-to-jpg',
    title: 'PDF para JPG',
    description: 'Extraia imagens ou converta páginas do PDF em imagens.',
    icon: ImageIcon,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-50',
    path: '/tool/pdf-to-jpg',
  },
  {
    id: 'protect',
    title: 'Proteger PDF',
    description: 'Adicione senha e criptografia para proteger documentos sensíveis.',
    icon: FileKey2,
    color: 'text-slate-500',
    bgColor: 'bg-slate-50',
    path: '/tool/protect',
  },
  {
    id: 'watermark',
    title: 'Marca d\'água',
    description: 'Carimbe texto ou imagens sobrepostas no seu documento PDF.',
    icon: Stamp,
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-50',
    path: '/tool/watermark',
  },
];
